### ISSUE TITLE
在项目中使用报错loading image for billboard: DeveloperError: Width must be less than or equal to the maximum texture size (0).  Check maximumTextureSize

### ISSUE THREAD

**Issue by Vickyeleven** [renshuo/cesium-plotting-symbol#30]
在vue项目中使用，根据文档调用api.报错。
![image](https://github.com/renshuo/cesium-plotting-symbol/assets/19465700/01cfcae8-4554-4759-be20-f49cb38b99e8)

**Comment by renshuo** [comment]
这个看不出来是什么问题，能否提供一下package.json以及操作过程？

**Comment by Vickyeleven** [comment]
> 这个看不出来是什么问题，能否提供一下package.json以及操作过程？

按照文档说明的直接引入
  "dependencies": {
    "@dvgis/cesium-map": "^2.5.0",
    "@jiaminghi/data-view": "^2.10.0",
    "@types/echarts": "^4.9.16",
    "axios": "0.19.2",
    "cesium": "1.80.0",
    "cesium-navigation-es6": "^1.1.7",
    "core-js": "^3.26.0",
    "d3": "~7.0.0",
    "dayjs": "^1.11.6",
    "echarts": "^5.2.1",
    "echarts-gl": "^2.0.8",
    "element-ui": "^2.15.2",
    "jquery": "^3.6.0",
    "js-cookie": "2.2.0",
    "lib-flexible": "^0.3.2",
    "mapv": "^2.0.62",
    "pako": "^2.1.0",
    "simplex-noise": "^3.0.0",
    "swiper": "^5.4.5",
    "v-calendar": "~2.3.2",
    "vue": "^2.7.8",
    "vue-awesome-swiper": "^4.1.1",
    "vue-fragment": "1.5.1",
    "vue-resize-observer": "^1.0.37",
    "vue-router": "^3.1.5",
    "vue-simple-uploader": "^0.7.6",
    "vuex": "^3.1.2",
    "vuex-persistedstate": "^4.1.0",
    "xlsx": "^0.17.3",
    "yapi-to-typescript": "^3.34.0",
    "zlib": "~1.0.5"
  },
  "devDependencies": {
    "@babel/core": "^7.18.6",
    "@babel/eslint-parser": "^7.18.2",
    "@commitlint/cli": "^16.3.0",
    "@commitlint/config-conventional": "^16.2.1",
    "@types/d3": "^7.4.0",
    "@types/pako": "^2.0.0",
    "@typescript-eslint/eslint-plugin": "^5.42.1",
    "@typescript-eslint/parser": "^5.42.1",
    "@vue/cli-plugin-babel": "^5.0.8",
    "@vue/cli-plugin-typescript": "^4.5.15",
    "@vue/cli-service": "^4.1.0",
    "@vue/eslint-config-prettier": "^5.0.0",
    "babel-eslint": "10.0.3",
    "babel-plugin-component": "^1.1.1",
    "compression-webpack-plugin": "^6.1.1",
    "copy-webpack-plugin": "^5.0.3",
    "eslint": "^8.19.0",
    "eslint-config-alloy": "^4.7.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^3.4.1",
    "eslint-plugin-vue": "^9.2.0",
    "fs": "0.0.1-security",
    "husky": "^8.0.1",
    "lint-staged": "^13.0.3",
    "mini-css-extract-plugin": "^2.6.0",
    "postcss-html": "^1.5.0",
    "postcss-scss": "^4.0.5",
    "prettier": "^1.19.1",
    "protobufjs": "^6.11.2",
    "px2rem-loader": "^0.1.9",
    "sass": "^1.23.7",
    "sass-loader": "^8.0.0",
    "stylelint": "^14.9.1",
    "stylelint-config-html": "^1.1.0",
    "stylelint-config-prettier": "^9.0.3",
    "stylelint-config-recess-order": "^3.0.0",
    "stylelint-config-standard": "^26.0.0",
    "svg-sprite-loader": "^4.3.0",
    "ts-loader": "~8.2.0",
    "typescript": "^4.8.4",
    "webpack": "^4.0.0",
    "webpack-bundle-analyzer": "^4.5.0"
  },
  "lint-staged": {
    "*.md": "prettier --write",
    "*.{ts,tsx,js,vue,scss}": "prettier --write",
    "*.{ts,tsx,js,vue}": "eslint --fix",
    "*.{vue,css,scss}": "stylelint --fix"
  },
  "browserslist": {
    "production": [
      "defaults",
      "last 10 versions",
      "not dead",
      "not op_mini all",
      "not ie 11"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }

**Comment by nemo-giser** [comment]
我也遇到这个问题了，我是在执行绘制point的操作时报的错，详细如下，希望有大神能够帮忙解决一下

DeveloperError: Width must be less than or equal to the maximum texture size (0).  Check maximumTextureSize.

Error
    at new DeveloperError (webpack-internal:///./node_modules/_@cesium_engine@2.2.0@@cesium/engine/Source/Core/DeveloperError.js:41:11)
    at new Texture (webpack-internal:///./node_modules/_@cesium_engine@2.2.0@@cesium/engine/Source/Renderer/Texture.js:66:11)
    at resizeAtlas (webpack-internal:///./node_modules/_@cesium_engine@2.2.0@@cesium/engine/Source/Scene/TextureAtlas.js:217:29)
    at addImage (webpack-internal:///./node_modules/_@cesium_engine@2.2.0@@cesium/engine/Source/Scene/TextureAtlas.js:305:5)
    at getIndex (webpack-internal:///./node_modules/_@cesium_engine@2.2.0@@cesium/engine/Source/Scene/TextureAtlas.js:315:3)
    at TextureAtlas.addImageSync (webpack-internal:///./node_modules/_@cesium_engine@2.2.0@@cesium/engine/Source/Scene/TextureAtlas.js:358:11)
    at addGlyphToTextureAtlas (webpack-internal:///./node_modules/_@cesium_engine@2.2.0@@cesium/engine/Source/Scene/LabelCollection.js:121:41)
    at rebindAllGlyphs (webpack-internal:///./node_modules/_@cesium_engine@2.2.0@@cesium/engine/Source/Scene/LabelCollection.js:218:11)
    at LabelCollection.update (webpack-internal:///./node_modules/_@cesium_engine@2.2.0@@cesium/engine/Source/Scene/LabelCollection.js:816:7)
    at EntityCluster.update (webpack-internal:///./node_modules/_@cesium_engine@2.2.0@@cesium/engine/Source/DataSources/EntityCluster.js:640:27)

**Comment by shuaiFengW** [comment]
> 我也遇到这个问题了，我在执行不够点的操作时报错，详细如下，希望有大神能够帮忙解决一下
> 
> DeveloperError：宽度必须小于或等于最大纹理大小 (0)。检查最大纹理尺寸。
> 
> 新纹理 (webpack-internal:///./node_modules/ @ _cesium_engine@2.2.0@@cesium/engine/Source/Core/DeveloperError.js:41:11) 处出现新 DeveloperError 错误 (webpack-internal:// /./node_modules/_ @cesium_engine@2.2.0@@cesium/engine/Source/Renderer/Texture.js:66:11) 在 resizeAtlas (webpack-internal:///./node_modules/ _@cesium_engine@2.2.0@ @cesium/engine/Source/Scene/TextureAtlas.js:217:29) 在 addImage (webpack-internal:///./node_modules/_ @cesium_engine@2.2.0@@cesium/engine/Source/Scene/TextureAtlas.js :305:5) 在 getIndex (webpack-internal:///./node_modules/ _@cesium_engine@2.2.0@@cesium/engine/Source/Scene/TextureAtlas.js:315:3) 在 TextureAtlas.addImageSync (webpack-内部:///./node_modules/_@cesium_engine@2.2.0@@cesium/engine/Source/Scene/TextureAtlas.js:358:11) 在 addGlyphToTextureAtlas (webpack-internal:///./node_modules/ _@cesium_engine@2.2.0@@cesium/engine/源/场景/LabelCollection.js:121:41) 在 rebindAllGlyphs (webpack-internal:///./node_modules/_ @cesium_engine@2.2.0@@cesium/engine/Source/Scene/LabelCollection.js:218:11) 在 LabelCollection.update (webpack-internal:///./node_modules/ _@cesium_engine@2.2.0@@cesium/engine/Source/Scene/LabelCollection.js:816:7) 在 EntityCluster.update (webpack-internal:/ //./node_modules/_ @cesium_engine@2.2.0@@cesium/engine/Source/DataSources/EntityCluster.js:640:27)

请问你解决这个问题了吗,我也遇到了这个问题

**Comment by shuaiFengW** [comment]
> 看这个不出来是什么问题，能否提供一下package.json以及操作过程？

{
  "_from": "cesium-plotting-symbol",
  "_id": "cesium-plotting-symbol@0.0.86",
  "_inBundle": false,
  "_integrity": "sha512-pBbrpJkmmJ5GdpsX9DI8YaW77frOk96gUMnn6MuA679jvcvr1QuDpjRa+f7xfLr2RyfWQgLWFMhW0Nl56/tH7w==",
  "_location": "/cesium-plotting-symbol",
  "_phantomChildren": {
    "@babel/parser": "7.21.3",
    "@zip.js/zip.js": "2.4.26",
    "autolinker": "4.0.0",
    "bitmap-sdf": "1.0.4",
    "dompurify": "3.0.3",
    "earcut": "2.2.4",
    "estree-walker": "2.0.2",
    "grapheme-splitter": "1.0.4",
    "jsep": "1.3.8",
    "kdbush": "4.0.2",
    "ktx-parse": "0.5.0",
    "lerc": "2.0.0",
    "mersenne-twister": "1.1.0",
    "meshoptimizer": "0.19.0",
    "nosleep.js": "0.12.0",
    "pako": "2.1.0",
    "postcss": "8.4.21",
    "protobufjs": "7.2.3",
    "rbush": "3.0.1",
    "source-map-js": "1.0.2",
    "topojson-client": "3.1.0",
    "urijs": "1.19.11"
  },
  "_requested": {
    "type": "tag",
    "registry": true,
    "raw": "cesium-plotting-symbol",
    "name": "cesium-plotting-symbol",
    "escapedName": "cesium-plotting-symbol",
    "rawSpec": "",
    "saveSpec": null,
    "fetchSpec": "latest"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "https://registry.npmmirror.com/cesium-plotting-symbol/-/cesium-plotting-symbol-0.0.86.tgz",
  "_shasum": "080ed4ed123d511ee08dd9d832d993dc76518422",
  "_spec": "cesium-plotting-symbol",
  "_where": "C:\\Users\\王帅峰\\Desktop\\cesiumProject",
  "author": {
    "name": "sren"
  },
  "bundleDependencies": false,
  "dependencies": {
    "@turf/turf": "^6.5.0",
    "@types/lodash": "^4.14.195",
    "bezier-js": "^6.1.3",
    "cesium": "^1.107.0",
    "file-saver": "^2.0.5",
    "keyboardjs": "^2.7.0",
    "lodash": "^4.17.21",
    "vue": "^3.3.4"
  },
  "deprecated": false,
  "description": "基于cesiumn的标绘，支持VUE3",
  "devDependencies": {
    "@vitejs/plugin-vue": "^3.2.0",
    "typescript": "^4.9.5",
    "vite": "^3.2.7",
    "vue-tsc": "^0.40.13"
  },
  "exports": {
    ".": {
      "import": "./dist/cesium-plotting-symbol.js",
      "require": "./dist/cesium-plotting-symbol.umd.cjs"
    },
    "./dist/style.css": {
      "import": "./dist/style.css",
      "require": "./dist/style.css"
    }
  },
  "files": [
    "dist"
  ],
  "keywords": [
    "cesium",
    "plotting",
    "symbol"
  ],
  "main": "./dist/cesium-plotting-symbol.umd.cjs",
  "module": "./dist/cesium-plotting-symbol.js",
  "name": "cesium-plotting-symbol",
  "private": false,
  "scripts": {
    "build": "vue-tsc --noEmit && vite build",
    "dev": "vite",
    "preview": "vite preview"
  },
  "type": "module",
  "version": "0.0.86"
}

请问是什么问题呀

**Comment by nemo-giser** [comment]
> > 我也遇到这个问题了，我在执行不够点的操作时报错，详细如下，希望有大神能够帮忙解决一下
> > DeveloperError：宽度必须小于或等于最大纹理大小 (0)。检查最大纹理尺寸。
> > 新纹理 (webpack-internal:///./node_modules/ @ _cesium_engine@2.2.0@@cesium/engine/Source/Core/DeveloperError.js:41:11) 处出现新 DeveloperError 错误 (webpack-internal:// /./node_modules/_ @cesium_engine@2.2.0@@cesium/engine/Source/Renderer/Texture.js:66:11) 在 resizeAtlas (webpack-internal:///./node_modules/ _@cesium_engine@2.2.0@ @cesium/engine/Source/Scene/TextureAtlas.js:217:29) 在 addImage (webpack-internal:///./node_modules/_ @cesium_engine@2.2.0@@cesium/engine/Source/Scene/TextureAtlas.js :305:5) 在 getIndex (webpack-internal:///./node_modules/ _@cesium_engine@2.2.0@@cesium/engine/Source/Scene/TextureAtlas.js:315:3) 在 TextureAtlas.addImageSync (webpack-内部:///./node_modules/_@cesium_engine@2.2.0@@cesium/engine/Source/Scene/TextureAtlas.js:358:11) 在 addGlyphToTextureAtlas (webpack-internal:///./node_modules/ _@cesium_engine@2.2.0@@cesium/engine/源/场景/LabelCollection.js:121:41) 在 rebindAllGlyphs (webpack-internal:///./node_modules/_ @cesium_engine@2.2.0@@cesium/engine/Source/Scene/LabelCollection.js:218:11) 在 LabelCollection.update (webpack-internal:///./node_modules/ _@cesium_engine@2.2.0@@cesium/engine/Source/Scene/LabelCollection.js:816:7) 在 EntityCluster.update (webpack-internal:/ //./node_modules/_ @cesium_engine@2.2.0@@cesium/engine/Source/DataSources/EntityCluster.js:640:27)
> 
> 请问你解决这个问题了吗,我也遇到了这个问题

暂时没有，绘制线和绘制面时都没问题，只有在绘制点的时候会报错，point里的各项参数设置我也试着调试了，未起作用。

**Comment by shuaiFengW** [comment]
> > > 我也遇到这个问题了，我在执行不够点的操作时报错，详细如下，希望有大神能够帮忙解决一下
> > > DeveloperError：宽度必须小于或等于最大纹理大小 (0)。检查最大纹理尺寸。
> > > 新纹理 (webpack-internal:///./node_modules/ @ _cesium_engine@2.2.0@@cesium/engine/Source/Core/DeveloperError.js:41:11) 处出现新 DeveloperError 错误 (webpack-internal:// /./node_modules/_ @cesium_engine@2.2.0@@cesium/engine/Source/Renderer/Texture.js:66:11) 在 resizeAtlas (webpack-internal:///./node_modules/ _@cesium_engine@2.2.0@ @cesium/engine/Source/Scene/TextureAtlas.js:217:29) 在 addImage (webpack-internal:///./node_modules/_ @cesium_engine@2.2.0@@cesium/engine/Source/Scene/TextureAtlas.js :305:5) 在 getIndex (webpack-internal:///./node_modules/ _@cesium_engine@2.2.0@@cesium/engine/Source/Scene/TextureAtlas.js:315:3) 在 TextureAtlas.addImageSync (webpack-内部:///./node_modules/_@cesium_engine@2.2.0@@cesium/engine/Source/Scene/TextureAtlas.js:358:11) 在 addGlyphToTextureAtlas (webpack-internal:///./node_modules/ _@cesium_engine@2.2.0@@cesium/engine/源/场景/LabelCollection.js:121:41) 在 rebindAllGlyphs (webpack-internal:///./node_modules/_ @cesium_engine@2.2.0@@cesium/engine/Source/Scene/LabelCollection.js:218:11) 在 LabelCollection.update (webpack-internal:///./node_modules/ _@cesium_engine@2.2.0@@cesium/engine/Source/Scene/LabelCollection.js:816:7) 在 EntityCluster.update (webpack-internal:/ //./node_modules/_ @cesium_engine@2.2.0@@cesium/engine/Source/DataSources/EntityCluster.js:640:27)
> > 
> > 
> > 请问你解决这个问题了吗,我也遇到了这个问题
> 
> 暂时没有，绘制线和绘制面时都没问题，只有在绘制点的时候会报错，point里的各项参数设置我也试着调试了，未起作用。

您那个cesium版本是什么呢,我这个是1.107.0版本,我这个好像使用什么都是报错
An error occurred while rendering.  Rendering has stopped.
DeveloperError: Width must be less than or equal to the maximum texture size (0).  Check maximumTextureSize.
和这个
Error loading image for billboard: DeveloperError: Width must be less than or equal to the maximum texture size (0).  Check maximumTextureSize.
请问怎么解决呢, 或者说, 您这个问题解决了吗?
万分感谢!

**Comment by nemo-giser** [comment]
> 
> 您那个cesium版本是什么呢,我这个是1.107.0版本,我这个好像使用什么都是报错 An error occurred while rendering. Rendering has stopped. DeveloperError: Width must be less than or equal to the maximum texture size (0). Check maximumTextureSize. 和这个 Error loading image for billboard: DeveloperError: Width must be less than or equal to the maximum texture size (0). Check maximumTextureSize. 请问怎么解决呢, 或者说, 您这个问题解决了吗? 万分感谢!

（1） 我的cesium版本是："cesium": "^1.92.0",
（2）经过我的测试，在我的项目中使用entities.add，方法如下时，可以正常绘制point：
viewer.entities.add({

        position: new Cesium.Cartesian3.fromDegrees(p[0], p[1], p[2]),
        point: {
          color: Cesium.Color.SKYBLUE,
          pixelSize: 10,
          outlineColor: Cesium.Color.YELLOW,
          outlineWidth: 5,
          heightReference: Cesium.HeightReference.CLAMP_TO_GROUND,
        },
}）
（3）先创建dataSource类，然后向其中添加entities元素时则会报错：
 this._dataSource = new Cesium.CustomDataSource("_dataSource");
 this.viewer.dataSources.add(this._dataSource);

this._dataSource.entities.add({
      position: new Cesium.Cartesian3.fromDegrees(p[0], p[1],p[2]),
      point: {
        color: Cesium.Color.SKYBLUE,
        pixelSize: 10,
        outlineColor: Cesium.Color.YELLOW,
        outlineWidth: 5,
        heightReference: Cesium.HeightReference.CLAMP_TO_GROUND,
      },
}）

**Comment by shuaiFengW** [comment]
> > 您那个cesium版本是什么呢,我这个是1.107.0版本,我这个好像使用什么都是报错 An error occurred while rendering. Rendering has stopped. DeveloperError: Width must be less than or equal to the maximum texture size (0). Check maximumTextureSize. 和这个 Error loading image for billboard: DeveloperError: Width must be less than or equal to the maximum texture size (0). Check maximumTextureSize. 请问怎么解决呢, 或者说, 您这个问题解决了吗? 万分感谢!
> 
> （1） 我的cesium版本是："cesium": "^1.92.0", （2）经过我的测试，在我的项目中使用entities.add，方法如下时，可以正常绘制point： viewer.entities.add({
> 
> ```
>     position: new Cesium.Cartesian3.fromDegrees(p[0], p[1], p[2]),
>     point: {
>       color: Cesium.Color.SKYBLUE,
>       pixelSize: 10,
>       outlineColor: Cesium.Color.YELLOW,
>       outlineWidth: 5,
>       heightReference: Cesium.HeightReference.CLAMP_TO_GROUND,
>     },
> ```
> 
> }） （3）先创建dataSource类，然后向其中添加entities元素时则会报错： this._dataSource = new Cesium.CustomDataSource("_dataSource"); this.viewer.dataSources.add(this._dataSource);
> 
> this._dataSource.entities.add({ position: new Cesium.Cartesian3.fromDegrees(p[0], p[1],p[2]), point: { color: Cesium.Color.SKYBLUE, pixelSize: 10, outlineColor: Cesium.Color.YELLOW, outlineWidth: 5, heightReference: Cesium.HeightReference.CLAMP_TO_GROUND, }, }）

您这个是自己项目里面的吧, 就是那个报错您解决了吗?

**Comment by nemo-giser** [comment]
暂未解决

**Comment by nemo-giser** [comment]
> 您这个是自己项目里面的吧, 就是那个报错您解决了吗?

暂未解决
